<h1>Designer Notes</h1>

<p>I am the designer of what is, to my knowledge, the only collectible card game on flags in the world, VEX. If you are not familiar with it, please contact me directly or review the product on the website, <a href="http://sixsided.com">www.sixsided.com</a>. If you are interested in flags, this is a great place to get started.
My design started out with a simple premise: I wanted to collect flags, in an affordable way. Obviously, collecting flag books or posters is one inexpensive way to get started, but unfortunately, although I have collected many flag books, I found this method lacking. Often, the images were too small to get any details, or the relationships between flags were restricted to the whims of the author.</p>
<p>The other extreme is to collect actual flags, with the standard size being two feet by three feet, or three by five. While I have done this, too, I found it to be horrible expensive. Depending on the material, a single 3 by 5 flag can cost $30 or more! Smaller sizes are available, (down to 4" by 6") but even these can get expensive with large purchases. So I settled on cards, in my opinion, the perfect size! What I learned while designing VEX was the many different shapes and constructions to flags. I developed a methodology by which almost every flag in the world can be catalogued using a combination decimal and binary system. The highlights of the system are shown below, but I'll only focus on the key design elements.</p>
<p>In starting, I discovered to my delight that the standard playing card in America is 2.5" by 3.5", and if I take a quarter of an inch around the card for flag information, I am left with 2" by 3" which happens to be the ratio (of width to length) for almost half of the 1000 flags in all editions of VEX. That brought me to my first decision: ratios. I wanted to show each flag in its true proportions, as specified by whatever authority so designates those things! Thus, the official flag ratio is in the upper left hand corner, and to easily review flags by ratio, I decided to color code each ratio.</p>
<p>Next, I noted that every flag in the world is a combination of two factors, colors and attributes. For the record, all flags in my game have one or more of the following colors. The colors are binary, in other words, a given color is either present or not. There are no shades, or lighter and darker colors. This was one possibly regret, but there were so many interpretations. I have intentionally restricted the color count in VEX to a maximum of six identified colors per card. The ten colors are: Blue (B); White (W); Red (R); Green (V); Yellow (Y); Black (N); Orange (O); Purple (P); Brown (M); Gray (G).</p>
<p>After colors, the other most important feature of the flag is its primary attribute. I have set up in my design ten primary attributes, which generally may be seen when viewed from the flag's fly, or the right edge of a flag. The numbers to the left of each primary attribute refer to how many times that attribute appears in 200 flags of the world, (from VEX DEX I, Nations of the World). This is a decimal based selection, and for primary attributes, only one number can (and must!) be chosen.</p>
<div class="well">
	<p>60 Primarily Solid ; 4 Vertical Bicolor ; 18 Horizontal Bicolor ; 3 TriBar Tricolor ; 23 Vertical Tricolor ; 59 Horizontal Tricolor ; 16 Striped Lines ; 2 Checked/Quartered ; 4 Saltire Cross ; 11 Diagonally ; 200 Primary Attributes in 200 Nations of the World, from VEX I</p>
</div>
<p>After primary attributes, the next most important feature of a flag is it's secondary attribute. These usually occur in the canton (upper left corner) area, but not always. Not all flags have secondary attributes, but if a flag does have one, it is only allowed one. This leads to some problems, such as flags with crosses and cantons, but these were few. Again, the numbers to the left of each secondary attribute refer to how many times that attribute appears in 200 flags of the world. (from VEX DEX I, Nations of the World). Like primary attributes, secondary attributes are also a decimal based selection, and only one number can be chosen.</p>
<div class="well">
	<p>4 Bordered ; 7 Vertical Bar ; 20 Triangle ; 13 Canton ; 2 Serrated ; 5 Union Jack ; 2 Gyronny ; 10 Cross ; 3 Diagonal Cross ; 9 Diagonal Bend ; 75 Secondary Attributes in 200 Nations of the World.</p>
</div>
<p>Lastly, my design incorporates tertiary attributes, that is to say, everything else. Flags can have 0, 1 or more tertiary attributes, and although several flags have none, many have more than 1. As in the case of colors, this is a binary based selection, in that either a flag has the chosen tertiary attribute or not, and like colors, more than one tertiary attribute can be chosen.</p>
<div class="well">
	<p>24 Fimbriated Lines ; 12 Sun Shaped Objects ; 16 Crescent or Moon ; 64 Star Shaped Objects ; 20 Disk or Circle ; 15 Text or Symbol ; 11 Plant Objects ; 16 Animal Objects ; 24 Man Made Objects ; 23 Shield/Coat of Arms ; 225 Tertiary Attributes in 200 Nations of the World, from VEX I.</p>
</div>
<p>Other information flowed naturally once I had the basics completed. I included the name of each political entity in the lower right hand corner (You can put your finger over it to memorize your flags!). Then I added information about where the flag is from along the bottom row, information that expanded with sub national flags (showing mother country and continent.) I wanted to show the dates in use of the flag (official dates, like the ratio, not just the first time proposed or seen), so that went along the right hand side. For national flags, I wanted to show the flag use, elaborated in the rules, and placed that matrix in the lower left hand corner. I added number for collecting, and then an elaborate points scheme to make for some interesting games. The point scheme formula is relatively easy: I'll leave that to the reader to figure out the exact calculation.</p>
<p>Thus to summarize, every card in VEX follows the same basic rules. Like colors, I have intentionally restricted the total attribute count in VEX to a maximum of six identified attributes (1,2 &amp; 3) per card.</p>
<ol>
	<li>Every flag has one and only one primary attribute, taken from the selections above. This is the "most important" feature of the flag. Examples include solid, stripes, and tribars.</li>
	<li>Every flag may or may not have exactly one secondary attribute, taken from the list above. This is a secondary design feature. Examples include diagonal lines and crosses.</li>
	<li>Every flag may have zero, one or more tertiary attributes, taken from the list above. Tertiary attributes include stars, crescents, coat-of-arms, and the like.</li>
	<li>Every flag is to be shown in its true ratio as specified by the government. Note that in certain places (like the UN) all flags are show equally proportioned).</li>
	<li>Every flag has dates shown, both the starting date and, if the flag is no longer in use, the ending date. Some dates are not available, so I had to approximate dates some times.</li>
	<li>All flags show the entity name, the entity location and, possibly, a usage matrix showing when the flag should be flown, otherwise, information about what sub entity a flag is.</li>
	</ol>
<p>I have found that this system is an excellent way of cataloging every flag in the world. There are thousands of flags in the world, and VEX has only printed off 1000. Using this system, the United States flag has colors RWB, Primary Attribute Striped, Secondary Attribute Canton, Tertiary Attribute Stars. So does Liberia. Malaysia adds color yellow, and the Tertiary Attribute Crescent. And so on.</p>
<p>Be sure to look at all the games included in VEX: There are five games in VEX I, five new games in VEX II &amp; III, and five more in VEX IV and V. Although you only need a single deck to play any of the games, once you start collecting, you'll be hooked, and you'll want the complete set. For additional questions about the design of VEX, drop me a note at <a href="mailto:VEX@SixSided.com">VEX@SixSided.com</a>. Enjoy your cards!</p>

